export const FoodMenuServices = {
    getData() {
        return [
            {
                id: 1001,
                category: "Chole Bhature",
                offers: "Super Saver Combo",
                item_name: "Chole Bhature + Gulab Jamun",
                details: "per plate",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10002,
                category: "Chole Bhature",
                offers: "Super Saver Combo",
                item_name: "Chole Bhature + Dry Fruit Lassi",
                details: "per plate",
                price: 169,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10003,
                category: "Chole Bhature",
                offers: "Super Saver Combo",
                item_name: "Chole Bhature + Gulab Jamun + Dry Fruit Lassi",
                details: "per plate",
                price: 199,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10004,
                category: "Chole Bhature",
                offers: "Super Saver Combo",
                item_name: "Chole Kulche + Dry Fruit Lassi",
                details: "per plate",
                price: 189,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10005,
                category: "Chole Bhature",
                offers: "Bhatura Singh Special",
                item_name: "Delhi ke Chole Bhature Full",
                details: "2 psc bhatura",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10006,
                category: "Chole Bhature",
                offers: "Bhatura Singh Special",
                item_name: "Delhi ke Chole Bhature Half",
                details: "1 psc bhatura",
                price: 79,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10007,
                category: "Chole Bhature",
                offers: "Thoda Extra",
                item_name: "Extra Chole",
                details: "",
                price: 49,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10008,
                category: "Chole Bhature",
                offers: "Thoda Extra",
                item_name: "Extra Kulcha",
                details: "1 psc",
                price: 39,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10009,
                category: "Chole Bhature",
                offers: "Thoda Extra",
                item_name: "Extra Bhatura",
                details: "1 psc",
                price: 29,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10010,
                category: "Chole Bhature",
                offers: "Kuch Meetha",
                item_name: "Gulab Jamun",
                details: "3 psc",
                price: 39,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10011,
                category: "Chole Bhature",
                offers: "Kuch Meetha",
                item_name: "Moong Dal Halwa",
                details: "per plate",
                price: 49,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10012,
                category: "Chole Bhature",
                offers: "Kuch Thanda",
                item_name: "Dry Fruit Lassi",
                details: "per glass",
                price: 79,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10013,
                category: "Chole Bhature",
                offers: "Kuch Thanda",
                item_name: "Gulab Rose Lassi",
                details: "per glass",
                price: 89,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10014,
                category: "Idli",
                offers: "Best Seller",
                item_name: "Idli (2 pcs)",
                details: "Fresh and soft idlis made from naturally fermented urad dal and parboiled rice. Served with cocunut chutney and sambhar.",
                price: 59,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10015,
                category: "Idli",
                offers: "Best Seller",
                item_name: "Sambhar Idli (2 pcs)",
                details: "Soft, fluffy idlis for a filling, delicious and healthy meal. Accompanied with coconut chutney and spicy & lightly tangy sambhar.",
                price: 69,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10016,
                category: "Idli",
                offers: "Recommended",
                item_name: "Ghee Idli (2 pcs)",
                details: "Quick, delicious and very filling. Pillowy soft, fresh idlis topped with pure ghee! Coconut chutney and sambhar on the side.",
                price: 69,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10017,
                category: "Idli",
                offers: "New Launch",
                item_name: "Butter Idli (2 pcs)",
                details: "Fluffy, fresh and filling idlis tossed in rich butter. Served with coconut chutney and sambhar.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10018,
                category: "Idli",
                offers: "New Launch",
                item_name: "Malgapodi Idli (2 pcs)",
                details: "Soft idlis tossed in spicy malgapodi masala, served with coconut chutney and sambhar.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10019,
                category: "Idli",
                offers: "Must Try",
                item_name: "Idli & Medu Vada",
                details: "Fresh and soft idli made from naturally fermented urad dal and parboiled rice & fried savoury lentil fritters, known as ‘medu vada’. Served with coconut chutney and sambhar.",
                price: 79,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10020,
                category: "Vada",
                offers: "Best Seller",
                item_name: "Medu Vada (2 pcs)",
                details: "Fried savory lentil fritters, known as ‘medu vada’, usually made in a doughnut shape, with a crispy exterior and soft interior. A popular food item in South Indian cuisine it is generally eaten as a breakfast or a snack and served with coconut chutney and sambhar.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10021,
                category: "Vada",
                offers: "Best Seller",
                item_name: "Sambhar Vada (2 pcs)",
                details: "Crispy crunchy savory fritters, deep fried in healthy soya bean oil known as medu vada, soaked in a generous helping of sambhar and served with a side of coconut chutney.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10022,
                category: "Vada",
                offers: "Best Seller",
                item_name: "Dahi Vada (2 pcs)",
                details: "Fried savory lentil fritters deep fried in healthy soybean oil, known as ‘medu vada’, dunked in curd and topped with sweet chutney and savory boondi.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10023,
                category: "Rice",
                offers: "Best Seller",
                item_name: "Lemon Rice",
                details: "Lemon Rice or Chitranna is a traditional South Indian rice preparation where cooked broken rice is flavoured with lemon juice and tempered with peanuts and curry leaves. It is served with coconut chutney.",
                price: 79,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10024,
                category: "Rice",
                offers: "Must Try",
                item_name: "Curd Rice",
                details: "A quintessential healthy dish to help you beat the heat! Curd is mixed with cooked broken rice and herbs, then tempered with spices. Served with a side of small papads and mixed pickle.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10025,
                category: "Rice",
                offers: "Must Try",
                item_name: "Sambhar Rice",
                details: "Sambhar rice or commonly known as Sambhar Sadam in South India, is a healthy vegetarian rice meal that is packed with the nutrients of broken rice, dal, mixed vegetables and served with coconut chutney.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10026,
                category: "Rice",
                offers: "New Launch",
                item_name: "Tomato Garlic Rice",
                details: "A spicy and tangy rice also known as Thakkali Sadam is loved by young and old alike. Broken rice cooked with fresh tomatoes and garlic combined with assorted common spices.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10027,
                category: "Rice",
                offers: "New Launch",
                item_name: "Tomato Ginger Rice",
                details: "A spicy and tangy rice also known as Thakkali Sadam is loved by young and old alike. Broken rice cooked with fresh tomatoes and ginger combined with assorted common spices.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10028,
                category: "Specials",
                offers: "Recommended",
                item_name: "Paniyaram (7 pcs)",
                details: "Pan fried dumplings made with fresh vegetables, fermented urad dal and rice batter. It is served with coconut chutney and sambhar.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10029,
                category: "Specials",
                offers: "Recommended",
                item_name: "Fried Idli (6 pcs)",
                details: "Crunchy on the outside, soft on the inside! Two fried idlis cut into 6 pieces and served with chutney and sambhar. Fried using soya bean oil, which contains healthy polyunsaturated fatty acids.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10030,
                category: "Specials",
                offers: "Recommended",
                item_name: "Fried Idli (9 pcs)",
                details: "Crunchy on the outside, soft on the inside! Three fried idlis cut into 9 pieces and served with chutney and sambhar. Fried using soya bean oil, which contains healthy polyunsaturated fatty acids.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10031,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, it is served with coconut chutney and sambhar.",
                price: 79,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10032,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Plain Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Cooked in healthy soya bean oil, it is served with coconut chutney and sambhar.",
                price: 89,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10033,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10034,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Paper Masala Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Cooked in healthy soya bean oil, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10035,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Cheese Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, with a generous sprinkling of shredded cheese, it is served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10036,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Cheese Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, with a generous sprinkling of shredded cheese, and spicy potato and onion masala, it is served with coconut chutney and sambhar. ",
                price: 149,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10037,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Butter Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein. Cooked in butter, it is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10038,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Butter Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in butter, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10039,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Butter Paper Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Cooked in butter, it is served with coconut chutney and sambhar.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10040,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Butter Paper Masala Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Cooked in butter with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 139,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10041,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Ghee Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in pure ghee, it is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10042,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Ghee Paper Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Cooked in pure ghee, it is served with coconut chutney and sambhar.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10043,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Ghee Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in pure ghee, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10044,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Ghee Paper Masala Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Cooked in pure ghee, with spicy potato and onion masala , it is served with coconut chutney and sambhar.",
                price: 139,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10045,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Mysore Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, with onion, garlic and tomato chutney, it is served with coconut chutney and sambhar.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10046,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Mysore Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, with onion, garlic and tomato chutney, and spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 139,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10047,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Mysore Cheese Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Cooked in healthy soya bean oil, with onion, garlic and tomato chutney, spicy potato and onion masala, and shredded cheese, it is served with coconut chutney and sambhar.",
                price: 189,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10048,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Malgapodi Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Prepared with malgapodi masala and cooked in healthy soya bean oil, it is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10049,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Malgapodi Paper Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Prepared with malgapodi masala and cooked in healthy soya bean oil, it is served with coconut chutney and sambhar.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10050,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Malgapodi Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Prepared with malgapodi masala and cooked in healthy soya bean oil, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10051,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Malgapodi Paper Masala Dosa (crisp)",
                details: "Rich in carbohydrates and protein. Prepared with malgapodi masala and cooked in healthy soya bean oil, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 139,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10052,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Dhania Plain Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Prepared with mint & coriander chutney; and cooked in healthy soya bean oil, it is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10053,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Dhania Masala Dosa (soft)",
                details: "Rich in carbohydrates and protein, it is sugar and gluten-free. Prepared with mint & coriander chutney; and cooked in healthy soya bean oil, with spicy potato and onion masala, it is served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10054,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Schezwan Plain Dosa (soft)",
                details: "A delicious fusion of Indian and Chinese flavours. Filled with spicy garlic schezwan sauce. Served with coconut chutney and sambhar.",
                price: 119,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10055,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Schezwan Paper Dosa (crisp)",
                details: "A delicious fusion of Indian and Chinese flavours. Filled with spicy garlic schezwan sauce. Served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10056,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Schezwan Masala Dosa (soft)",
                details: "A delicious fusion of Indian and Chinese flavours. Filled with spicy garlic schezwan sauce and flavorful potato masala. Served with coconut chutney and sambhar.",
                price: 139,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10057,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Schezwan Paper Masala Dosa (crisp)",
                details: "A delicious fusion of Indian and Chinese flavours. Filled with spicy garlic schezwan sauce and flavorful potato masala. Served with coconut chutney and sambhar.",
                price: 149,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10058,
                category: "Dosa",
                offers: "Recommended",
                item_name: "Schezwan Cheese Masala Dosa (soft)",
                details: "A delicious fusion of Indian and Chinese flavours. Filled with spicy garlic schezwan sauce, flavorful potato masala and shredded cheese, it is served with coconut chutney and sambhar.",
                price: 189,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10059,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Onion Uttapam",
                details: "Fresh and soft pancake made from idli batter with onions as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10060,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Veggie Uttapam",
                details: "Fresh and soft pancake made from idli batter with mixed vegetables as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10061,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Tomato Uttapam",
                details: "Fresh and soft pancake made from idli batter with tomatoes as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10062,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Coconut Uttapam",
                details: "Fresh and soft pancake made from idli batter with coconut as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 109,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10063,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Cheese Onion Uttapam",
                details: "Fresh and soft pancake made from idli batter with shredded cheese and onions as toppings. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 159,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10064,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Cheese Veggie Uttapam",
                details: "Fresh and soft pancake made from idli batter with shredded cheese and mixed veggetables as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 159,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10065,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Cheese Tomato Uttapam",
                details: "Fresh and soft pancake made from idli batter with shredded cheese and tomatoes as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 159,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10066,
                category: "Uttapam",
                offers: "Must Try",
                item_name: "Onion Podi Uttapam",
                details: "Fresh and soft pancake made from idli batter with onions & malgapodi masala as topping. Rich in carbohydrates and protein, it is cooked in healthy soya bean oil, and is sugar and gluten-free. It is served with coconut chutney and sambhar.",
                price: 129,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10067,
                category: "Dessert",
                offers: "Must Try",
                item_name: "Coconut Barfi (2 pcs)",
                details: "Made with freshly desiccated coconut, sugar and flavored with cardamom. It is also known as thengai burfi in South India.",
                price: 59,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10068,
                category: "Dessert",
                offers: "Must Try",
                item_name: "Coconut Barfi (4 pcs)",
                details: "Made with freshly desiccated coconut, sugar and flavored with cardamom. It is also known as thengai burfi in South India.",
                price: 99,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10068,
                category: "Dessert",
                offers: "Must Try",
                item_name: "Angoori Gulab Jamun (7 pcs)",
                details: "Made with milk solids (Khoa), desi ghee, sugar and cardamom - Bite-sized goodness of Gulab Jamun.",
                price: 39,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10068,
                category: "Dessert",
                offers: "Must Try",
                item_name: "Angoori Gulab Jamun with Ice Cream (7 pcs)",
                details: "Made with milk solids (Khoa), desi ghee, sugar and cardamom - Bite-sized goodness of Gulab Jamun served with vanilla icecream",
                price: 59,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10069,
                category: "Thoda Extra",
                offers: "NA",
                item_name: "Green Chilli (5 gms)",
                details: "Chopped green chillies",
                price: 10,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10070,
                category: "Thoda Extra",
                offers: "NA",
                item_name: "Aloo Masala (150 gms)",
                details: "Spicy potato masala",
                price: 30,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10071,
                category: "Thoda Extra",
                offers: "NA",
                item_name: "Sambhar (250 ml)",
                details: "Lentil-based vegetable stew with mixed vegetables, tamarind, herbs and spices",
                price: 30,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10072,
                category: "Thoda Extra",
                offers: "NA",
                item_name: "Coconut Chutney (100 ml)",
                details: "Coconut chutney with ginger, herbs and spices",
                price: 40,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10073,
                category: "Thoda Extra",
                offers: "NA",
                item_name: "Green Chutney (100 ml)",
                details: "Coriander and mint chutney with herbs and spices",
                price: 40,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            },
            {
                id: 10074,
                category: "Thoda Extra",
                offers: "NA",
                item_name: "Red Chutney (100 ml)",
                details: "Tomato and red chilli with ginger and spices",
                price: 40,
                receipe: "",
                images: "",
                updated_by: "admin",
                updated_at: "2024-28-27"
            }
        ];
    },

    getFoodMenuSmall() {
        return Promise.resolve(this.getData().slice(0, 10));
    },

    getFoodMenuMedium() {
        return Promise.resolve(this.getData().slice(0, 50));
    },

    getFoodMenuLarge() {
        return Promise.resolve(this.getData().slice(0, 200));
    },

    getFoodMenuXLarge() {
        return Promise.resolve(this.getData());
    },
}